# Generated by Django 5.0.6 on 2024-05-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_product_seller_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_username", models.CharField(max_length=200)),
                ("amount", models.IntegerField()),
                ("stripe_payment_intent", models.CharField(max_length=200)),
                ("has_paid", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("update_on", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="myapp.product"
                    ),
                ),
            ],
        ),
    ]
